server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend-a:8000/;
    }

    location /ai/ {
        proxy_pass http://backend-b:8001/;
    }
}