"""erd_schema_update

Revision ID: 35e0d6d35009
Revises: 4958469f0622
Create Date: 2026-04-23 12:21:48.737341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35e0d6d35009'
down_revision: Union[str, Sequence[str], None] = '4958469f0622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('required_step',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('toast_message', sa.Text(), nullable=True),
    sa.Column('template_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('project', sa.Column('duration_month', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('project', sa.Column('constraint', sa.Text(), nullable=True))
    op.add_column('project', sa.Column('is_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('project', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('project', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('project', 'duration')
    op.add_column('step', sa.Column('parent_step_id', sa.UUID(), nullable=True))
    op.add_column('step', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'step', 'step', ['parent_step_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'step', type_='foreignkey')
    op.drop_column('step', 'created_at')
    op.drop_column('step', 'parent_step_id')
    op.add_column('project', sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('project', 'updated_at')
    op.drop_column('project', 'is_deleted')
    op.drop_column('project', 'is_completed')
    op.drop_column('project', 'constraint')
    op.drop_column('project', 'description')
    op.drop_column('project', 'duration_month')
    op.drop_table('required_step')
    # ### end Alembic commands ###
