"""step_content: drop guide, rename template to template_url

Revision ID: 4958469f0622
Revises: a2aef58231c7
Create Date: 2026-04-09 14:41:00.020382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4958469f0622'
down_revision: Union[str, Sequence[str], None] = 'a2aef58231c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step_content', sa.Column('template_url', sa.String(), nullable=True))
    op.drop_column('step_content', 'template')
    op.drop_column('step_content', 'guide')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step_content', sa.Column('guide', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('step_content', sa.Column('template', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('step_content', 'template_url')
    # ### end Alembic commands ###
