"""project_stages_status_to_is_active

Revision ID: 4ea0a5ce7207
Revises: e2a873e24aff
Create Date: 2026-04-25 21:07:23.497934

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4ea0a5ce7207"
down_revision: Union[str, Sequence[str], None] = "e2a873e24aff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1) is_active 컬럼 추가 (nullable, default false)
    op.add_column(
        "project_stages",
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # 2) 기존 status='ACTIVE' → is_active=true 변환
    op.execute("UPDATE project_stages SET is_active = true WHERE status = 'ACTIVE'")
    # 3) status 컬럼 삭제
    op.drop_column("project_stages", "status")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_stages",
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("project_stages", "is_active")
    # ### end Alembic commands ###
