"""add_share_token_to_project

Revision ID: 6bd360bbd9f0
Revises: f860518d6539
Create Date: 2026-05-11 19:27:00.210152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bd360bbd9f0'
down_revision: Union[str, Sequence[str], None] = 'f860518d6539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('share_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_project_share_token'), 'project', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_share_token'), table_name='project')
    op.drop_column('project', 'share_token')
    # ### end Alembic commands ###
