"""sync_models_with_db

Revision ID: 93fb6cb87eb3
Revises: daca5ae15977
Create Date: 2026-04-26 16:50:01.642811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93fb6cb87eb3'
down_revision: Union[str, Sequence[str], None] = 'daca5ae15977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'stage', ['sequence'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stage', type_='unique')
    # ### end Alembic commands ###
