"""add_default_content_to_required_step

Revision ID: a66f09fc3d71
Revises: ababec8477d2
Create Date: 2026-05-07 22:18:37.589901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a66f09fc3d71'
down_revision: Union[str, Sequence[str], None] = 'ababec8477d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('required_step', sa.Column('default_mentoring', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('required_step', sa.Column('default_dictionary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # 기존 required_step 레코드에 seed content 반영
    from sqlalchemy.orm import Session
    from app.core.seeds.required_step import run
    bind = op.get_bind()
    with Session(bind=bind) as db:
        run(db)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('required_step', 'default_dictionary')
    op.drop_column('required_step', 'default_mentoring')
    # ### end Alembic commands ###
