"""seed_required_step_data

Revision ID: ababec8477d2
Revises: 59036a725c7c
Create Date: 2026-05-07 14:29:04.274242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ababec8477d2'
down_revision: Union[str, Sequence[str], None] = '59036a725c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    from app.core.database import SessionLocal
    from app.core.seeds.required_step import run
    db = SessionLocal()
    try:
        run(db)
    finally:
        db.close()

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
