"""seed_required_step_data

Revision ID: ababec8477d2
Revises: d2b8f4c6e1a3
Create Date: 2026-05-07 14:29:04.274242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ababec8477d2'
down_revision: Union[str, Sequence[str], None] = 'd2b8f4c6e1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    from sqlalchemy.orm import Session
    from app.core.seeds.required_step import run

    bind = op.get_bind()
    with Session(bind=bind) as db:
        run(db)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
