"""seed_required_step_data

Revision ID: ababec8477d2
Revises: d2b8f4c6e1a3
Create Date: 2026-05-07 14:29:04.274242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ababec8477d2'
down_revision: Union[str, Sequence[str], None] = 'd2b8f4c6e1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # default_mentoring / default_dictionary 컬럼은 a66f09fc3d71 마이그레이션에서
    # 추가된 후 run(db)가 호출되므로 여기서는 실행하지 않는다.
    pass

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
