"""add_stage_sequence_unique

Revision ID: b37190a455b1
Revises: 897a468e3c9f
Create Date: 2026-04-23 22:58:02.973556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b37190a455b1'
down_revision: Union[str, Sequence[str], None] = '897a468e3c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'stage', ['sequence'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stage', type_='unique')
    # ### end Alembic commands ###
