"""add_ai_columns_and_project_required_step_status

Revision ID: e2a873e24aff
Revises: dddb486a5e76
Create Date: 2026-04-24 02:19:38.610211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2a873e24aff'
down_revision: Union[str, Sequence[str], None] = 'dddb486a5e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_required_step_status',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('required_step_id', sa.UUID(), nullable=False),
    sa.Column('is_fulfilled', sa.Boolean(), nullable=False),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['required_step_id'], ['required_step.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'required_step_id')
    )
    op.add_column('required_step', sa.Column('goal', sa.Text(), server_default='', nullable=False))
    op.add_column('required_step', sa.Column('entry_criteria', sa.Text(), server_default='', nullable=False))
    op.add_column('required_step', sa.Column('fulfillment_aspects', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('required_step', sa.Column('fulfillment_threshold', sa.Integer(), server_default='2', nullable=False))
    op.add_column('required_step', sa.Column('doj_reference', sa.Text(), nullable=True))
    op.drop_constraint(op.f('stage_sequence_key'), 'stage', type_='unique')
    op.add_column('step', sa.Column('belonging_required_step_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'step', 'required_step', ['belonging_required_step_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'step', type_='foreignkey')
    op.drop_column('step', 'belonging_required_step_id')
    op.create_unique_constraint(op.f('stage_sequence_key'), 'stage', ['sequence'], postgresql_nulls_not_distinct=False)
    op.drop_column('required_step', 'doj_reference')
    op.drop_column('required_step', 'fulfillment_threshold')
    op.drop_column('required_step', 'fulfillment_aspects')
    op.drop_column('required_step', 'entry_criteria')
    op.drop_column('required_step', 'goal')
    op.drop_table('project_required_step_status')
    # ### end Alembic commands ###
