"""replace_template_content_with_url

Revision ID: f860518d6539
Revises: a66f09fc3d71
Create Date: 2026-05-11 02:34:00.585020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f860518d6539'
down_revision: Union[str, Sequence[str], None] = 'a66f09fc3d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('required_step', sa.Column('template_url', sa.String(), nullable=True))
    op.drop_column('step_content', 'template_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step_content', sa.Column('template_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('required_step', sa.Column('template_content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('required_step', 'template_url')
    # ### end Alembic commands ###
